default:
  image: amazoncorretto:17.0.3

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  CI_JOB_NAME: "testt"

stages:
  - test
  - build

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"

test:
  stage: test
  script:
   ./mvnw test
  cache:
    paths:
      - ./target
      - ./.m2

docker_build:
  stage: build
  script:
    - docker build -t my-docker-image .
    # - docker build -t example.com/example-image:latest .
    # - docker push example.com/example-image:latest
